### ISSUE TITLE
Mixed Spotlight No Longer Casts Shadows on Avatar

### ISSUE THREAD

**Issue by owlboy** [cubedparadox/Cubeds-Unity-Shaders#21]
It seems that I no longer receive shadows on my avatar from the mixed spot lights in The Pug. This may be related to #20, but I'm not sure. Directional lights do work still.

I can switch to an avatar with the older iteration of the shader, and I do have shadows from myself and other objects.

**Comment by TCL987** [comment]
This has been fixed in c903b2d and will be included in the next release.

**Comment by TCL987** [comment]
This has been fixed in 0.20.
