### ISSUE TITLE
Double-sided mesh support

### ISSUE THREAD

**Issue by jaxry** [cubedparadox/Cubeds-Unity-Shaders#23]
The Flat Lit Toon shader currently backface culls polygons. Culling is required to create the outline effect, but this means that the shader doesn't render inside faces for double-sided meshes (e.g. hair or skirts). If the user chooses to use no outlines, would it be helpful to expose to the Material Inspector a parameter which controls culling? Is such a thing even possible?

**Comment by TCL987** [comment]
You can replicate the behavior of having back face culling disabled by
enabling tinted outlines, setting the width to 0, and the tint colour to
white.
