### ISSUE TITLE
can not figure out to add these shaders to unity

### ISSUE THREAD

**Issue by Joe6032** [cubedparadox/Cubeds-Unity-Shaders#26]

**Comment by MrQ89** [comment]
_You can get the latest release [here](https://github.com/cubedparadox/Cubeds-Unity-Shaders/releases)
Currently built for Unity 5.6.3p1
Installation: Add it to your unity assets (drag and drop in the package, or go to "Assets/Import Package/Custom Package" at the top and from there you can find it in your shaders drop down list automatically._

As it says right in the description simply click that link, download the unitypackage file and then drag it into the Project window in Unity and it will be installed
