### ISSUE TITLE
More dynamic light changes?

### ISSUE THREAD

**Issue by Mimikitty** [cubedparadox/Cubeds-Unity-Shaders#3]
Im not sure if this is the proper way to word it but allow better changes between dark and bright light on real time lights. This might work well already on baked/light probes. I'm not sure

**Comment by cubedparadox** [comment]
fixed in https://github.com/cubedparadox/Cubeds-Unity-Shaders/commit/b46cc468cb7e3f88aa1f7175bdc83768933df7e3
