### ISSUE TITLE
Having Issue adding Shader to Unity

### ISSUE THREAD

**Issue by Meoows** [cubedparadox/Cubeds-Unity-Shaders#30]
I downloaded the package unzipped it and when I open unity to add the package it doesn't seem to show the file to add it? it's only showing empty folders, not sure what I'm doing wrong. 
PLEASE HELP!

**Comment by MrQ89** [comment]
_You can get the latest release here
Currently built for Unity 5.6.3p1
Installation: Add it to your unity assets (drag and drop in the package, or go to "Assets/Import Package/Custom Package" at the top and from there you can find it in your shaders drop down list automatically._

As it says right in the description simply click that link, download the unitypackage file and then drag it into the Project window in Unity and it will be installed
