### ISSUE TITLE
Images in the Readme are Broken

### ISSUE THREAD

**Issue by owlboy** [cubedparadox/Cubeds-Unity-Shaders#33]
Some of the images in the readme are broken.

**Comment by jamesli3397** [comment]
Error downloading object: Assets/Cubed's Unity Shaders/UnityChan/License/License Logo/LUUL_LOGO_rules02.psd (79bf933): Smudge error: Error downloading Assets/Cubed's Unity Shaders/UnityChan/License/License Logo/LUUL_LOGO_rules02.psd (79bf93338777bcd70b3fe49367c8676626b651c300c98b7188a65ab29e51eced): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Apparently VRChat users pushed this user over their 1GB quota.

**Comment by cubedparadox** [comment]
Fixed in https://github.com/cubedparadox/Cubeds-Unity-Shaders/commit/30254918914a476128126afeb1cb0d28d08e1e45
