### ISSUE TITLE
Shader is not lit by Mixed Lights

### ISSUE THREAD

**Issue by TCL987** [cubedparadox/Cubeds-Unity-Shaders#4]
The shader doesn't appear to be lit in real-time by mixed lights.

Example:
![image](https://user-images.githubusercontent.com/3751840/29008628-37f30bfa-7acf-11e7-9085-5f460e65a87c.png)

**Comment by cubedparadox** [comment]
fixed in https://github.com/cubedparadox/Cubeds-Unity-Shaders/commit/44d74db4d0d13d1b07358bcb9da4a25572b4d153
