### ISSUE TITLE
No options for the flat lit toon shader

### ISSUE THREAD

**Issue by bendertherobo** [cubedparadox/Cubeds-Unity-Shaders#42]
when i select the flat lit toon shader the inspector is blank, i cant add outlines, change the rendering mode, anything, the other cubed shaders show options properly, ive tried deleting, reimporting, then restarting my unity but no luck, materials that the shader was put on before this started happening still show their options, but new ones do not

**Comment by cubedparadox** [comment]
This doesn't sound like an issue with the shader, and I can't repro it. make sure you've loaded the editor scripts for the toon shader, and not just the shader files.
