### ISSUE TITLE
Arkward clipping, when using rendering mode: transparent

### ISSUE THREAD

**Issue by SupraLP** [cubedparadox/Cubeds-Unity-Shaders#45]
When I tried to make a slightly transparent object my object started looking arkward and I have no idea, why; https://clips.twitch.tv/VastHonestMagpieTwitchRaid?tt_medium=create

I have no special settings in the camera nor in the materials, they're just plain flat lit toon, with rendering mode set to transparent.

**Comment by GenesisAria** [comment]
Try opening up the shader code and replacing ZWrite [_ZWrite] with ZWrite On
