### ISSUE TITLE
Feature Request: Outline Color

### ISSUE THREAD

**Issue by dtupper** [cubedparadox/Cubeds-Unity-Shaders#5]
Pretty simple (at least in concept) -- allow for setting the color of the outline.

**Comment by cubedparadox** [comment]
would being able to set tint color of the outline be sufficient, or do you need to override color completely? and in the override case, would you be expecting properly lit outlines, or unlit colors?

**Comment by dtupper** [comment]
Tint color of the outline would be fine. Full override of the outline might be a bit overkill, but hey, if you wanna implement it I wouldn't mind.

**Comment by cubedparadox** [comment]
ok, that's much simpler to implement. added to task list.

**Comment by TCL987** [comment]
I suggested this in VRChat; posting it here so you don't forget it.

The shader GUI should use a drop-down menu to select between:
- No Outline
- Tinted Outline (Tint Colour is multiplied by the texture colour.)
- Coloured Outline (Outline Colour is not multiplied by the texture colour.)

**Comment by cubedparadox** [comment]
Fixed in https://github.com/cubedparadox/Cubeds-Unity-Shaders/commit/95393a8cf57db0b5fb1bb241d0145e662aceb66d
