### ISSUE TITLE
Point lights shadows don't follow the shadow value set in the shader for Flat Lit Toon

### ISSUE THREAD

**Issue by MrQ89** [cubedparadox/Cubeds-Unity-Shaders#6]
Even if Shadow is set to 0 the shadow cast from point lights are cast onto the shader

**Comment by cubedparadox** [comment]
fixed in https://github.com/cubedparadox/Cubeds-Unity-Shaders/commit/44d74db4d0d13d1b07358bcb9da4a25572b4d153
