### ISSUE TITLE
Excessive draw calls

### ISSUE THREAD

**Issue by dtupper** [cubedparadox/Cubeds-Unity-Shaders#7]
The shader apparently makes 3 draw calls for every material this is applied to, currently. Since the current VRC meme is to reduce draw calls to the absolute minimum, I'd suggest an attempt to reduce this to one.

I'd talk to TCL for further details, as he understands it better than I do.

**Comment by cubedparadox** [comment]
fixed in https://github.com/cubedparadox/Cubeds-Unity-Shaders/commit/44d74db4d0d13d1b07358bcb9da4a25572b4d153

**Comment by owlboy** [comment]
Woohoo!

**Comment by owlboy** [comment]
Wait a sec, was the Unity Package updated? I Just went to import what I thought was the latest version and it says "Nothing to import!"
